// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcnzdcgsrrmnhdgfoohh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbnpkY2dzcnJtbmhkZ2Zvb2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1OTE2NzYsImV4cCI6MjA5MjE2NzY3Nn0.F8J4KK8DjxqIJIgJtahFWyk1nfTY4GLHB_rJlz-g91A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});